Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Private Sub Check1_Click()
待求点坐标.Show
End Sub

Private Sub Check10_Click()
    If Check10.Value = 1 Then
        link(m).Active = True
    ElseIf Check10.Value = 0 Then
        link(m).Active = False
    End If
End Sub

Private Sub Check2_Click()
If Check2.Value = 1 Then
    Check3.Enabled = False
    Check8.Enabled = False
    If Option1 Then
        link(m).ch(1) = True        '表示构件上尾端点出现复合铰链
        num_of_ch = num_of_ch + 1
        link(m).ch_num(1) = num_of_ch
        For i = 0 To m - 1
        If link(i).ch(0) = True Or link(i).ch(1) = True Then
            Check6.Enabled = True
        End If
    Next
    ElseIf Option2 Then
        link(m).ch(0) = True        '表示三副构件上第二副出现复合铰链
        num_of_ch = num_of_ch + 1
        link(m).ch_num(0) = num_of_ch
        Check6.Enabled = False
        Check8.Enabled = False
    End If
ElseIf Check2.Value = 0 Then
    Check3.Enabled = True
    Check6.Enabled = False
    If Option1 Then
        link(m).ch(1) = False       '表示取消构件上尾端点的复合铰链
        num_of_ch = num_of_ch - 1
        link(m).ch_num(1) = 0
        For i = 1 To m - 1
            If Option4.Value And link(i).RE Then
                Check8.Enabled = True
            ElseIf Option5.Value And link(i).PE Then
                Check8.Enabled = True
            End If
        Next
    ElseIf Option2 Then
        link(m).ch(0) = False       '表示取消构件三副构件上第2点的复合铰链
        num_of_ch = num_of_ch - 1
        link(m).ch_num(0) = 0
        Check8.Value = 0
        Check8.Enabled = False
    End If
End If

End Sub

Private Sub Check3_Click()
If Check3.Value = 1 And Option4.Value Then
    Check2.Enabled = False
    Text7.Enabled = True
    Text8.Enabled = True
    Text7.BackColor = &HFF00&: Text8.BackColor = &HFF00&
    Check5.Enabled = False
    Check5.Value = 0
    Text12.Text = "": Text13.Text = ""
    Text12.Enabled = False: Text13.Enabled = False
    Text12.BackColor = &H80000004: Text13.BackColor = &H80000004
    If link(m).PorR(0) = 2 Then
        Check10.Visible = True
    End If
ElseIf Check3.Value = 1 And Option5.Value Then
    Text9.Enabled = True
    Text10.Enabled = True
    Text9.BackColor = &HFF00&: Text10.BackColor = &HFF00&
    Check5.Enabled = False
    Check10.Value = 0
    Check10.Visible = False
ElseIf Check3.Value = 0 Then
    If Option4 Then
        Check2.Enabled = True
    End If
    Text7.Text = ""
    Text8.Text = ""
    Text9.Text = ""
    Text10.Text = ""
    Text7.Enabled = False
    Text8.Enabled = False
    Text7.BackColor = &H80000004: Text8.BackColor = &H80000004
    Text9.Enabled = False
    Text10.Enabled = False
    Text9.BackColor = &H80000004: Text10.BackColor = &H80000004
    Check5.Enabled = True
    Check10.Value = 0
    Check10.Visible = False
End If
End Sub

Private Sub Check4_Click()
If Check4.Value = 1 Then
    Check5.Enabled = False
    Check5.Value = 0
    Check9.Value = 0
    Check9.Enabled = False
    link(m).ch(1) = True        '表示三副构件上尾副出现复合铰链
    num_of_ch = num_of_ch + 1
    link(m).ch_num(1) = num_of_ch
    For i = 0 To m - 1
        If link(i).ch(0) = True Or link(i).ch(1) = True Then
            Check7.Enabled = True
        End If
    Next
ElseIf Check4.Value = 0 Then
    Check5.Enabled = True
    Check7.Enabled = False
    link(m).ch(1) = False        '表示取消三副构件上尾副出现复合铰链
    num_of_ch = num_of_ch - 1
    link(m).ch_num(1) = 0
    For i = 1 To m - 1
            If Option6.Value And link(i).RE Then
                Check9.Enabled = True
            ElseIf Option5.Value And link(i).PE Then
                Check9.Enabled = True
            End If
    Next
End If
End Sub

Private Sub Check5_Click()
If Check5.Value = 1 And Option6.Value Then
    Text12.Enabled = True
    Text13.Enabled = True
    Text12.BackColor = &HFF00&: Text13.BackColor = &HFF00&
    Check3.Enabled = False
    Check3.Value = 0
    Text7.Text = "": Text8.Text = ""
ElseIf Check5.Value = 1 And Option7.Value Then
    Text14.Enabled = True
    Text15.Enabled = True
    Text14.BackColor = &HFF00&: Text15.BackColor = &HFF00&
    Check3.Enabled = False
    Check3.Value = 0
End If
If Check5.Value = 0 Then
    Text12.Text = ""
    Text13.Text = ""
    Text14.Text = ""
    Text15.Text = ""
    Text12.Enabled = False
    Text13.Enabled = False
    Text12.BackColor = &H80000004: Text13.BackColor = &H80000004
    Text14.Enabled = False
    Text15.Enabled = False
    Text14.BackColor = &H80000004: Text15.BackColor = &H80000004
    Check3.Enabled = True
End If
End Sub

Private Sub Check6_Click()
If Check6.Value = 1 Then
    If Option1 Then
        link(m).ch(1) = False       '表示前一复选框选中造成的ch(1)=True取消
    ElseIf Option2 Then
        link(m).ch(0) = False       '表示前一复选框选中造成的ch(0)=True取消
    End If
    Text16.Enabled = True
    Text16.BackColor = &HFF00&
ElseIf Check6.Value = 0 Then
    If Option1 Then
        link(m).ch(1) = True        '表示本复选框取消选中，应使得ch(1)=True
    ElseIf Option2 Then
        link(m).ch(0) = True        '表示本复选框取消选中，应使得ch(0)=True
    End If         '
    Text16.Enabled = False
    Text16.BackColor = &H80000004
End If
End Sub

Private Sub Check7_Click()
If Check7.Value = 1 Then
    If Option1 Then
        link(m).ch(1) = False       '表示前一复选框选中造成的ch(1)=True取消
    ElseIf Option2 Then
        link(m).ch(0) = False       '表示前一复选框选中造成的ch(0)=True取消
    End If
    Text17.Enabled = True
    Text17.BackColor = &HFF00&
ElseIf Check7.Value = 0 Then
    If Option1 Then
        link(m).ch(1) = True        '表示本复选框取消选中，应使得ch(1)=True
    ElseIf Option2 Then
        link(m).ch(0) = True        '表示本复选框取消选中，应使得ch(0)=True
    End If
    Text17.Enabled = False
    Text17.BackColor = &H80000004
End If
End Sub

Private Sub Check8_Click()
    If Check8.Value = 1 Then
        Text18.Enabled = True
        Text18.BackColor = &HFF00&
    ElseIf Check8.Value = 0 Then
        Text18.Enabled = False
        Text18.BackColor = &H80000004
    End If
End Sub

Private Sub Check9_Click()
    If Check9.Value = 1 Then
        Text19.Enabled = True
        Text19.BackColor = &HFF00&
    ElseIf Check9.Value = 0 Then
        Text19.Enabled = False
        Text19.BackColor = &H80000004
    End If
End Sub

Private Sub Command2_Click()
Set swApp = CreateObject("sldworks.application")
Set Part = swApp.ActiveDoc

 If Option1.Value And Text1 <> "" Then      '用户确定是二副
    link(m).L(0) = Text1
    If Option4.Value Then                     '尾副为R
        link(m).PorR(1) = 2
        If Check3.Value = 1 And Text7 <> "" And Text8 <> "" Then    '尾副为固定R副
            link(m).Xf = Text7
            link(m).Yf = Text8
            Unload Form2
            turn2nex.Show
        ElseIf Check3.Value = 0 Then
            If Check6.Value = 1 And Text16 <> "" Then
                link(m).ch_junction_num = Text16.Text
                Unload Form2
                turn2nex.Show
            ElseIf Check6.Value = 0 Then
                If Check8.Value = 1 And Text18 <> "" Then
                    link(m).Empty_junction_num = Text18.Text
                    Unload Form2
                    turn2nex.Show
                ElseIf Check8.Value = 0 Then
                    Unload Form2
                    turn2nex.Show
                Else
                    wrong.Show
                    wrongmsg = True
                End If
            Else
                wrong.Show
                wrongmsg = True
            End If
        Else
            wrong.Show
            wrongmsg = True
        End If
    ElseIf link(m).PorR(0) = 1 And Option5.Value And Text6 <> "" Then         'PP构件
        link(m).PorR(1) = 1
        link(m).beta(0) = Text6
        If Check3.Value = 1 And Text9 <> "" And Text10 <> "" Then
            link(m).D = Text9
            link(m).alpha = Text10
            link(m).P_fixed = True
            Unload Form2
            turn2nex.Show
        ElseIf Check3.Value = 0 Then
            If Check8.Value = 1 And Text18 <> "" Then
                link(m).Empty_junction_num = Text18.Text
                Unload Form2
                turn2nex.Show
            ElseIf Check8.Value = 0 Then
                Unload Form2
                turn2nex.Show
            Else
                wrong.Show
                wrongmsg = True
            End If
        Else
            wrong.Show
            wrongmsg = True
        End If
    ElseIf link(m).PorR(0) = 2 And Option5.Value Then                     'RP构件
        link(m).PorR(1) = 1
        If Check3.Value = 1 And Text9 <> "" And Text10 <> "" Then
            link(m).D = Text9
            link(m).alpha = Text10
            link(m).P_fixed = True
            Unload Form2
            turn2nex.Show
        ElseIf Check3.Value = 0 Then
            If Check8.Value = 1 And Text18 <> "" Then
                link(m).Empty_junction_num = Text18.Text
                Unload Form2
                turn2nex.Show
            ElseIf Check8.Value = 0 Then
                Unload Form2
                turn2nex.Show
            Else
                wrong.Show
                wrongmsg = True
            End If
        Else
            wrong.Show
            wrongmsg = True
        End If
    Else
          wrong.Show
          wrongmsg = True
    End If
 ElseIf Option2.Value Then                      '三副构件
    link(m).PE = False
    link(m).RE = False
    If Text5.Enabled = True Then
        If Text5 = "" Then
            wrong.Show
            wrongmsg = True
        Else
            link(m).beta(0) = Text5
            GoTo A
        End If
    Else
A:  If Text2 <> "" And Text3 <> "" And Text4 <> "" Then
        link(m).L(0) = Text4
        link(m).L(1) = Text3
        link(m).L(2) = Text2
        If Option4.Value Then
            link(m).RE = True        '表示空余的R副出现
            link(m).PorR(2) = 2
            If Check3.Value = 1 And Text7 <> "" And Text8 <> "" Then
                link(m).Xf = Text7
                link(m).Yf = Text8
                link(m).fixed(0) = True
                link(m).RE = False        '表示空余的R副已固定，之后的函数End_Link_Judge不用判断
                If Option6.Value Then
                    link(m).PorR(1) = 2
                    If Check5.Value = 1 And Text12 <> "" And Text13 <> "" Then
                        link(m).Xf = Text12
                        link(m).Yf = Text13
                        link(m).fixed(1) = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                ElseIf Option7.Value And Text11 <> "" Then
                    link(m).PorR(1) = 1
                    link(m).beta(1) = Text11
                    If Check5.Value = 1 And Text14 <> "" And Text15 <> "" Then
                        link(m).D = Text14
                        link(m).alpha = Text15
                        link(m).fixed(1) = True
                        link(m).P_fixed = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                Else
                    wrong.Show
                    wrongmsg = True
                End If
                    
            ElseIf Check3.Value = 0 Then
                If Option6.Value Then
                    link(m).PorR(1) = 2
                    If Check5.Value = 1 And Text12 <> "" And Text13 <> "" Then
                        link(m).Xf = Text12
                        link(m).Yf = Text13
                        link(m).fixed(1) = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                ElseIf Option7.Value And Text11 <> "" Then
                    link(m).PorR(1) = 1
                    link(m).beta(1) = Text11
                    If Check5.Value = 1 And Text14 <> "" And Text15 <> "" Then
                        link(m).D = Text14
                        link(m).alpha = Text15
                        link(m).fixed(1) = True
                        link(m).P_fixed = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                Else
                    wrong.Show
                    wrongmsg = True
                End If
            Else
                wrong.Show
                wrongmsg = True
            End If
        ElseIf Option5.Value And Text6 <> "" Then
            link(m).PE = True        '表示空余的P副出现
            link(m).PorR(2) = 1
            link(m).beta(2) = Text6
            If Check3.Value = 1 And Text9 <> "" And Text10 <> "" Then
                link(m).D = Text9
                link(m).alpha = Text10
                link(m).P_fixed = True
                link(m).fixed(0) = True
                link(m).PE = False        '表示空余的P副已固定，之后的函数End_Link_Judge不用判断
                If Option6.Value Then
                    link(m).PorR(1) = 2
                    If Check5.Value = 1 And Text12 <> "" And Text13 <> "" Then
                        link(m).Xf = Text12
                        link(m).Yf = Text13
                        link(m).fixed(1) = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                ElseIf Option7.Value And Text11 <> "" Then
                    link(m).PorR(1) = 1
                    link(m).beta(1) = Text11
                    If Check5.Value = 1 And Text14 <> "" And Text15 <> "" Then
                        link(m).D = Text14
                        link(m).alpha = Text15
                        link(m).fixed(1) = True
                        link(m).P_fixed = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                Else
                    wrong.Show
                    wrongmsg = True
                End If

            ElseIf Check3.Value = 0 Then
                If Option6.Value Then
                    link(m).PorR(1) = 2
                    If Check5.Value = 1 And Text12 <> "" And Text13 <> "" Then
                        link(m).Xf = Text12
                        link(m).Yf = Text13
                        link(m).fixed(1) = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                ElseIf Option7.Value And Text11 <> "" Then
                    link(m).PorR(1) = 1
                    link(m).beta(1) = Text11
                    If Check5.Value = 1 And Text14 <> "" And Text15 <> "" Then
                        link(m).D = Text14
                        link(m).alpha = Text15
                        link(m).fixed(1) = True
                        link(m).P_fixed = True
                        Unload Form2
                        turn2nex.Show
                    ElseIf Check5.Value = 0 Then
                        If Check7.Value = 1 And Text17 <> "" Then
                            link(m).ch_junction_num = Text17.Text
                            Unload Form2
                            turn2nex.Show
                        ElseIf Check7.Value = 0 Then
                            If Check9.Value = 1 And Text19 <> "" Then
                                link(m).Empty_junction_num = Text19.Text
                                Unload Form2
                                turn2nex.Show
                            ElseIf Check9.Value = 0 Then
                                Unload Form2
                                turn2nex.Show
                            Else
                                wrong.Show
                                wrongmsg = True
                            End If
                        Else
                            wrong.Show
                            wrongmsg = True
                        End If
                    Else
                        wrong.Show
                        wrongmsg = True
                    End If
                Else
                    wrong.Show
                    wrongmsg = True
                End If
            Else
                wrong.Show
                wrongmsg = True
            End If
        Else
            wrong.Show
            wrongmsg = True
        End If
    Else
        wrong.Show
        wrongmsg = True
    End If
    End If
 Else
    wrong.Show
    wrongmsg = True
 End If
' If wrongmsg = False And link(m).PorR(2) > 0 And link(m).P_fixed = False And link(m).Xf = 0 Then
'        num_of_Empty = num_of_Empty + 1
'        link(m).Empty_num = num_of_Empty
' End If
If wrongmsg = False Then
    For n = 1 To 3     '三草图,每次循环进入一个草图
        If n = 1 Then
            no_dimen = no_dimen - no_dimen_Shift
        ElseIf n = 3 Then
            no_dimen = no_dimen + no_dimen_Shift
        End If
        boolstatus = Part.Extension.SelectByID2("草图" & n, "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
        Part.EditSketch
        If Xr = 0 And Yr = 0 Then       '不是待求构件
            Draw_2D.draw_lines
        Else                            '是待求构件，计划绘制完待求构件后将Xr，Yr清零，就可以了
            link(m).TBS = True
            Draw_2D.draw_lines
            If n = 1 Then
                Draw_2D_TBS.Change_Form         '只是改变块的形式，使之与待求构件相同
            End If
        End If
        Part.SketchManager.InsertSketch True
    Next
    If To_Be_Replace Then       '转去替换待求构件的过程，并添加驱动速度的尺寸部分
        Draw_2D_TBS.Replace
        
    End If
End If
'测试输出
 datatest.Text1 = ""
 For i = 0 To m
    datatest.Text1 = datatest.Text1 & "##" & link(i).PorR(0)
    'datatest.Text2 = link
 Next
 'datatest.Text2 = link(m).Xf
 'datatest.Text2 = UorT
 'datatest.Text2 = link(m).Empty_num
 datatest.Text2 = dimen_tobe_Delete(1)
 datatest.Show
End Sub

Private Sub Command3_Click()
    Form2.Visible = False
    planar.Show
End Sub

Private Sub Form_Load()
ReDim Preserve link(m + 1)

If link(m).PorR(1) Then   '保证误关form2的情况下不会错误计数
    m = m + 1
End If
Label20.Caption = m
Frame3.Enabled = False
Text2.Enabled = False
Text3.Enabled = False
Text4.Enabled = False
Text5.Enabled = False
Text6.Enabled = False
Text7.Enabled = False
Text8.Enabled = False
Text9.Enabled = False
Text10.Enabled = False
Text11.Enabled = False
Text12.Enabled = False
Text13.Enabled = False
Text14.Enabled = False
Text15.Enabled = False
Text16.Enabled = False
Text17.Enabled = False
Text18.Enabled = False
Text19.Enabled = False
Frame3.Enabled = False
Check2.Enabled = False
Check6.Enabled = False
Check8.Enabled = False
Check3.Enabled = False
Command3.Enabled = False
If m = 0 Then
    Check10.Visible = True
Else
    Check10.Visible = False
End If
If TBS = True Then
    Check1.Enabled = False
    Check1.Caption = "是否为待求构件（已确定待求构件）"
End If
If m >= 1 Then
    If link(m - 1).Xf Or link(m - 1).P_fixed Then   '上一副有固定副
        If link(m - 1).fixed(1) = True Then     '三副构件尾副是固定副
            If Is_Empty_PorR = True Then
                link(m).PorR(0) = 1
            Else
                link(m).PorR(0) = 2
            End If
        ElseIf link(m - 1).fixed(0) = True Then      '三副构件②副是固定副
            link(m).PorR(0) = link(m - 1).PorR(1)     '首副和上一尾副相同
        Else
            If Is_Empty_PorR = True Then
                link(m).PorR(0) = 1
            Else
                link(m).PorR(0) = 2
            End If
        End If
    Else
        link(m).PorR(0) = link(m - 1).PorR(1)     '首副和上一尾副相同
    End If
End If
link(m).PorR(2) = 0   '应该是对每个构件的一个初始化作用，我也忘记了。。
End Sub

Private Sub Option1_Click()
Text1.Enabled = True
Text1.BackColor = &HFF00&
Text2.Enabled = False
Text3.Enabled = False
Text4.Enabled = False
Text5.Enabled = False
Text5.BackColor = &H80000004
Text2.BackColor = &H80000004: Text3.BackColor = &H80000004: Text4.BackColor = &H80000004
Text2 = ""
Text3 = ""
Text4 = ""
Text5 = ""
Text11 = "": Text12 = "": Text13 = "": Text14 = "": Text15 = "": Text17 = "": Text19 = ""
Text11.BackColor = &H80000004
Option6.Value = 0: Option7.Value = 0
Check4.Value = 0: Check5.Value = 0: Check7.Value = 0: Check9.Value = 0
Frame3.Enabled = False
Frame3.Visible = False
End Sub

Private Sub Option2_Click()
Text1.Enabled = False
Text1.BackColor = &H80000004
Text1 = ""
Text2.Enabled = True
Text3.Enabled = True
Text4.Enabled = True
Text2.BackColor = &HFF00&: Text3.BackColor = &HFF00&: Text4.BackColor = &HFF00&
Frame3.Enabled = True
Frame3.Visible = True
Check2.Value = 0
Check3.Value = 0
Check4.Enabled = False
Check7.Enabled = False
Check9.Enabled = False
End Sub

Private Sub Option3_Click()
Text1.Enabled = False
Text1 = ""
Text2.Enabled = True
Text3.Enabled = True
Text4.Enabled = True
Frame3.Enabled = True
Frame3.Visible = True
Check4.Enabled = False
Check7.Enabled = False
Check9.Enabled = False
End Sub

Private Sub Option4_Click()
    Text6.Enabled = False
    Text6.BackColor = &H80000004
    Check2.Enabled = True
    Check3.Enabled = True
    If Option1 Then
        For i = 0 To m - 1
            If link(i).PE = True Or link(i).RE = True Then
                Check8.Enabled = True
            End If
        Next
    ElseIf Option2 Then
        Check8.Value = 0
        Check8.Enabled = False
    End If
    Check3.Value = 0
    Text6 = ""
    Text9.Text = ""
    Text10.Text = ""
If Option4.Value Then
End If
End Sub

Private Sub Option5_Click()
    Text6.Enabled = True
    Text6.BackColor = &HFF00&
    If Option1 And link(m).PorR(0) = 2 Then     '对于二副，若首副为R，则不用输入P副夹角
        Text6.Enabled = False
        Text6.BackColor = &H80000004
    End If
    Check2.Enabled = False
    Check6.Enabled = False
    If Option1 Then
        For i = 0 To m - 1
            If link(i).PE = True Or link(i).RE = True Then
                Check8.Enabled = True
            End If
        Next
    ElseIf Option2 Then
        Check8.Value = 0
        Check8.Enabled = False
    End If
    Check3.Enabled = True
    Check3.Value = 0  '感觉这里触发了check3的点击事件
    Check2.Value = 0
    Check6.Value = 0
    Text7.Text = ""
    Text8.Text = ""
End Sub

Private Sub Option6_Click()
    Text11.Enabled = False
    Text11.BackColor = &H80000004
    Check4.Enabled = True
    Check5.Enabled = True
    For i = 0 To m - 1
        If link(i).PE = True Or link(i).RE = True Then
            Check9.Enabled = True
        End If
    Next
    Check5.Value = 0
    Text11 = ""
    Text14.Text = ""
    Text15.Text = ""
    Check10.Value = 0
    Check10.Visible = False
End Sub

Private Sub Option7_Click()
    Text11.Enabled = True
    Text11.BackColor = &HFF00&
    Check4.Enabled = False
    Check7.Enabled = False
    For i = 0 To m - 1
        If link(i).PE = True Or link(i).RE = True Then
            Check9.Enabled = True
        End If
    Next
    Check5.Value = 0
    Check4.Value = 0
    Check7.Value = 0
    Text12.Text = ""
    Text13.Text = ""
    Check10.Value = 0
    Check10.Visible = False
End Sub

Private Sub Text16_Change()
If Text16 <> "" Then
    If Text16 > num_of_ch Then
        MsgBox "超出范围，请修改序号"
        Text16 = ""
    End If
End If
End Sub

Private Sub Text17_Change()
If Text17 <> "" Then
    If Text17 > num_of_ch Then
        MsgBox "超出范围，请修改序号"
        Text17 = ""
    End If
End If
End Sub

Private Sub Text18_Change()
If Text18 <> "" Then
    If Text18 > num_of_Empty Then
        MsgBox "超出范围，请修改序号"
        Text18 = ""
    End If
End If
End Sub

Private Sub Text19_Change()
If Text19 <> "" Then
    If Text19 > num_of_Empty Then
        MsgBox "超出范围，请修改序号"
        Text19 = ""
    End If
End If
End Sub

Private Sub Text4_Change()
If m > 0 Then
    If Text4 <> "" And link(m - 1).PorR(1) = 1 Then
        Text5.Enabled = True
        Text5.BackColor = &HFF00&
    End If
End If
End Sub
